all:
	c++ -I /usr/include/boost/ -I /usr/include/pcl-1.6/ -I /usr/include/eigen3 tracklets.h getLabels.cpp -o build/getLabels.out -L /usr/lib/ -lboost_serialization -lpcl_common -lpcl_io -lpcl_filters -w
